local diff = require("vim_coach.diff")

describe("diff.hunks", function()
  it("returns no hunks for equal text", function()
    assert.same({}, diff.hunks({ "a", "b" }, { "a", "b" }))
  end)

  it("returns line hunks", function()
    local h = diff.hunks({ "a", "b", "c" }, { "a", "x", "c" })
    assert.equals(1, #h)
    assert.same({ a = 2, na = 1, b = 2, nb = 1 }, h[1])
  end)
end)

describe("diff.affix", function()
  it("finds common prefix and suffix without overlap", function()
    assert.same({ 3, 2 }, { diff.affix("abcXYde", "abcZde") })
    assert.same({ 3, 0 }, { diff.affix("abc", "abcd") })
    assert.same({ 2, 0 }, { diff.affix("aa", "aaa") })
  end)

  it("does not split UTF-8 characters", function()
    local pre, suf = diff.affix("a\u{00e9}b", "a\u{00e8}b") -- e-acute vs e-grave share a lead byte
    assert.equals(1, pre)
    assert.equals(1, suf)
  end)
end)

describe("diff.classify", function()
  it("none", function()
    assert.equals("none", diff.classify({ "a" }, { "a" }).kind)
  end)

  it("intra-line replacement", function()
    local s = diff.classify({ 'x = "hello"' }, { 'x = "bye"' })
    assert.equals("intra", s.kind)
    local it = s.items[1]
    assert.equals(1, it.row)
    assert.equals("hello", it.old)
    assert.equals("bye", it.new)
  end)

  it("per_line with shared facts", function()
    local s = diff.classify({ "a", "b", "c" }, { "- a", "- b", "- c" })
    assert.equals("per_line", s.kind)
    assert.is_true(s.group.insert)
    assert.is_true(s.group.same_new)
    assert.is_true(s.group.pos.bol)
    assert.is_true(s.group.contiguous)
    assert.equals(3, s.scale)
  end)

  it("indent shape", function()
    local s = diff.classify({ "a", "b" }, { "  a", "  b" })
    assert.is_true(s.group.indent)
  end)

  it("deleted lines", function()
    local s = diff.classify({ "a", "b", "c", "d" }, { "a", "d" })
    assert.equals("del_lines", s.kind)
    assert.equals(2, s.row)
    assert.equals(2, s.n)
  end)

  it("duplicated lines below and above", function()
    local s = diff.classify({ "a", "b" }, { "a", "a", "b" })
    assert.equals("dup", s.kind)
    assert.equals("below", s.where)
    assert.equals(1, s.row)
    local s2 = diff.classify({ "a", "b" }, { "a", "b", "b" })
    assert.equals("dup", s2.kind)
    assert.equals(2, s2.row)
  end)

  it("moved lines", function()
    local s = diff.classify({ "a", "b", "c" }, { "b", "c", "a" })
    assert.equals("move", s.kind)
    assert.equals(1, s.from)
    assert.equals(1, s.n)
    assert.equals(3, s.dest)
    local s2 = diff.classify({ "a", "b", "c" }, { "c", "a", "b" })
    assert.equals("move", s2.kind)
    assert.equals(3, s2.from)
    assert.equals(0, s2.dest)
  end)

  it("joined lines", function()
    local s = diff.classify({ "a", "b", "c" }, { "a b", "c" })
    assert.equals("join", s.kind)
    assert.equals(2, s.n)
  end)

  it("other for mixed shapes", function()
    assert.equals("other", diff.classify({ "a" }, { "b", "c" }).kind)
  end)

  it("signature ignores position but keeps the inserted text", function()
    local a = diff.classify({ "one two" }, { "one XY" })
    local b = diff.classify({ "three four" }, { "three XY" })
    assert.equals(diff.signature(a), diff.signature(b))
    local c = diff.classify({ "one two" }, { "one ZZ" })
    assert.are_not.equal(diff.signature(a), diff.signature(c))
  end)
end)
